# Generated by Django 5.1 on 2024-08-19 19:37

import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(help_text='The City the User lives in', max_length=255, verbose_name='City')),
                ('zip_code', models.CharField(help_text='The zip code of the City the User lives in', max_length=25, verbose_name='ZIP Code')),
                ('street', models.CharField(help_text='The street the User lives in', max_length=255, verbose_name='Street')),
                ('house_number', models.CharField(help_text='The house number of the User', max_length=255, verbose_name='House Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
