# Generated by Django 5.1 on 2024-08-14 06:27

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.UUID('1b6f251d-7334-46e2-89ab-cf0690333915'), editable=False, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(help_text='The City the User lives in', max_length=255, verbose_name='City')),
                ('zip_code', models.CharField(help_text='The zip code of the City the User lives in', max_length=25, verbose_name='ZIP Code')),
                ('street', models.CharField(help_text='The street the User lives in', max_length=255, verbose_name='Street')),
                ('house_number', models.CharField(help_text='The street the User lives in', max_length=255, verbose_name='Street')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
