# Generated by Django 5.1 on 2024-08-28 07:53

import cloudinary.models
import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(blank=True, help_text='The City the User lives in', max_length=255, null=True, verbose_name='City')),
                ('zip_code', models.CharField(blank=True, help_text='The zip code of the City the User lives in', max_length=25, null=True, verbose_name='ZIP Code')),
                ('street', models.CharField(blank=True, help_text='The street the User lives in', max_length=255, null=True, verbose_name='Street')),
                ('house_number', models.CharField(blank=True, help_text='The house number of the User', max_length=255, null=True, verbose_name='House Number')),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
