# Generated by Django 5.1 on 2024-08-14 07:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f6874f90-34d3-4485-b6f1-558bffbd8943'), editable=False, unique=True),
        ),
    ]
