# Generated by Django 5.1 on 2024-08-14 07:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='house_number',
            field=models.CharField(help_text='The house number of the User', max_length=255, verbose_name='House Number'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7a49f066-c91b-4859-a246-ceac2c8c5fad'), editable=False, unique=True),
        ),
    ]
