# Generated by Django 5.1 on 2024-08-16 14:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_house_number_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7eb191a-12d1-41ad-afb8-02bca45ec081'), editable=False, unique=True),
        ),
    ]
