# Generated by Django 5.1 on 2024-08-16 14:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8fb2208c-ac8d-4567-9fc2-33b56e507a42'), editable=False, unique=True),
        ),
    ]
