# Generated by Django 5.1 on 2024-08-16 14:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e5871119-2119-494b-b9b7-aaa2bf56eb5b'), editable=False, unique=True),
        ),
    ]
