# Generated by Django 5.1 on 2024-08-17 07:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a27f9c5d-2952-4c35-a0d4-c93cda29c436'), editable=False, unique=True),
        ),
    ]
