# Generated by Django 5.1 on 2024-08-18 14:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('48019e5a-3db2-4a62-a518-a27b1da518f0'), editable=False, unique=True),
        ),
    ]
