version: "3.9"

networks:
  feather_network:
    external: true

services:
  nginx:
    container_name: nginx
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./static:/app/static
      - logs_store:/app/var/log/nginx
    depends_on:
      - client
      - server
      - mailpit
    privileged: true
    networks:
      - feather_network

  server:
    container_name: server
    build:
      context: .
      dockerfile: ./docker/local/server/Dockerfile
    env_file:
      - ./.envs/.env.local
    # ports:
    #   - 8000:8000
    expose:
      - "8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
      - mailpit
    privileged: true
    networks:
      - feather_network

  postgres:
    container_name: postgres
    image: postgres:16.3-bullseye
    env_file:
      - ./.envs/.env.local
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    privileged: true
    networks:
      - feather_network

  client:
    container_name: client
    build:
      context: ./client
      dockerfile: ./docker/local/Dockerfile
    # ports:
    #   - 3000:3000
    expose:
      - "3000"
    env_file:
      - ./.envs/.env.local
    volumes:
      - ./client/src:/app/src
      - /app/node_modules
    privileged: true
    networks:
      - feather_network

  mailpit:
    container_name: mailpit
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailpit_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    privileged: true
    networks:
      - feather_network

  redis:
    container_name: redis
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    depends_on:
      - server
    privileged: true
    networks:
      - feather_network

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3.13.6-management-alpine"
    ports:
      - "5672:5672"
      - "15672:15672"
    privileged: true
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - feather_network

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: ./docker/local/server/Dockerfile
    command: celery -A server worker --hostname=server_worker --loglevel=info -Q email_tasks
    env_file:
      - ./.envs/.env.local
    volumes:
      - ./:/app
    depends_on:
      - server
      - rabbitmq
      - redis
    privileged: true
    networks:
      - feather_network

  flower:
    container_name: flower
    image: mher/flower
    ports:
      - 5555:5555
    env_file:
      - ./.envs/.env.local
    privileged: true
    networks:
      - feather_network

volumes:
  postgres_data: {}
  mailpit_data: {}
  logs_store: {}
  redis_data: {}
  rabbitmq_data: {}
