server:
  port: 9000

spring:
  application:
    name: authserver
  datasource:
    url: jdbc:mysql://localhost:3306/auth-db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true

springdoc:
  api-docs:
    path: /auth-server/v3/api-docs
  swagger-ui:
    path: /auth-server/swagger-ui.html
    csrf:
      cookie-name: XSRF-TOKEN
      header-name: X-XSRF-TOKEN
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true

app:
  frontend:
    uri: http://localhost:8000
    client-id: oidc-client
    redirect-uri:
      login: http://localhost:8000/callback
      refresh: http://localhost:8000/silent-renew
      logout: http://localhost:8000
