server:
  port: 8000

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8000/feather/authserver/oauth2/jwks

springdoc:
  swagger-ui:
    path: /openapi/swagger-ui.html
    csrf:
      cookie-name: XSRF-TOKEN
      enabled: true
      header-name: X-XSRF-TOKEN
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        display-name: API Gateway Service

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: read-only
    health:
      probes:
        enabled: true

app:
  authserver:
    url: http://localhost:9000
  frontend:
    url: http://localhost:3000
