server:
  port: 8000

spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8000/feather/authserver/oauth2/jwks

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - gateway
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
  info:
    env:
      enabled: true
  endpoint:
    gateway:
      access: read-only
    health:
      probes:
        enabled: true
