server:
  port: 8080

spring:
  application:
    name: profile
  datasource:
    username: user
    password: password
    url: jdbc:mysql://localhost:3307/profile-db
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090
