server:
  port: 9090

spring:
  application:
    name: authserver
  datasource:
    url: jdbc:mysql://localhost:3306/auth-db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
