services:
  authserver-db:
    container_name: authserver-db
    image: mysql:8.0-debian
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=auth-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    networks:
      - feather-network
  rabbit:
    container_name: rabbitmq
    build:
      context: ./../../dockerfiles/rabbitmq
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - feather-network
