services:
  authserver-db:
    container_name: authserver-db
    image: mysql:9.2.0-oraclelinux9
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=auth-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./../../../data/auth-db:/var/lib/mysql
    networks:
      - feather-network
